apiVersion: v1
kind: Service
metadata:
  name: simple-project-service
spec:
  type: LoadBalancer
  selector:
    app: simple-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
